### ISSUE TITLE
2023.2 version fails with `poetry`.

### ISSUE THREAD

**Issue by ilyagr** [FHPythonUtils/AnsiToImg#9]
I get:

```
$ poetry add ansitoimg@latest
$ poetry install
$ poetry run -- ansitoimg
Traceback (most recent call last):
  File "/home/ilyagr/.cache/pypoetry/virtualenvs/jj-docs-ZVbGoaMc-py3.11/bin/ansitoimg", line 5, in <module>
    from ansitoimg import cli
  File "/home/ilyagr/.cache/pypoetry/virtualenvs/jj-docs-ZVbGoaMc-py3.11/lib/python3.11/site-packages/ansitoimg/__init__.py", line 10, in <module>
    from ansitoimg.render import (
  File "/home/ilyagr/.cache/pypoetry/virtualenvs/jj-docs-ZVbGoaMc-py3.11/lib/python3.11/site-packages/ansitoimg/render.py", line 15, in <module>
    from ansitoimg.utils import TEXT_HEIGHT, TEXT_WIDTH, TITLE, WIDTH_DEFAULT, _resolveWidth
ImportError: cannot import name '_resolveWidth' from 'ansitoimg.utils' (/home/ilyagr/.cache/pypoetry/virtualenvs/jj-docs-ZVbGoaMc-py3.11/lib/python3.11/site-packages/ansitoimg/utils.py)
```

I don't get such problems if I `poetry add ansitoimg@2023.1`.

OS: `Linux dragon 5.15.124-20253-g52415d073cb4 #1 SMP PREEMPT Mon Aug 21 18:50:56 PDT 2023 x86_64 GNU/Linux`

Python:

```
$ poetry run -- python --version
Python 3.11.4
$ poetry --version
Poetry (version 1.5.1)
```

**Comment by FredHappyface** [comment]
Cheers for opening this! It appears I was far to aggressive in my code clean-up. I'll get this reverted and fixed in the next version. I'll aim for sometime over the next week (should be sooner)

**Comment by FredHappyface** [comment]
Should be fixed in https://pypi.org/project/ansitoimg/2023.3/. Thanks again for raising this :)
